<h1>Numpy, esta es otra librería super importantem, esta es la que se encarga de todo lo que tiene que ver con las operaciones matemáticas, es una libre ría cientifica</h1>
<h2>Jamás la he visto, pero me causa mucha motivación, ojalá no me de tan duro</h2>

In [6]:
#Antes de importar numpy, es pertinente instalarlo, usando pip install numpy, en la consola
import numpy as np #De esta manera no solo importamos numpy sino que imporetamos las listas np
#Lo primero que vamos a hacer es crear una matriz con Numpy
#Matriz ND es parecida a una lista, solo que esta tiene un tamaño fijo y sus elementos son del mismo tipo


In [7]:
lista_np=np.array([0,1,2,3,4,5,6,7,8,9]) #De esta manera se lanza una lista 

In [8]:
#Podemos llamar los elementos de estos arreglos usansdo el indice como las listas
lista_np[4]

4

In [9]:
#Miremos que tipo de elemento me muestra este arreglo
type(lista_np) # me muestra que es numpy.ndarray

numpy.ndarray

In [10]:
#Para saber el tipo de dato que tiene la Matriz, podemos usar el siguiente metodo
lista_np.dtype #nos va a mostrar que el arreglo tiene enteeros de 64 bits

dtype('int64')

In [11]:
#Para ver el tamaño de la matriz, podemos usar el metodo size
lista_np.size 

10

In [12]:
#Para vevr el numero de dimensiones que tiene la matriz, usamos el metodo .ndim
lista_np.ndim #En te caso esta matriz es de una dimensión por eso imprime el 1

1

In [13]:
#PAra ver el numero dee atributos por dimensión usamos el atributo .shape
lista_np.shape #como este solo tiene una dimensión pues solo me mostrará el número de la primera dimensión, lo muestra en forma de tupla

(10,)

In [14]:
#También se puede crear una matriz usando números decimales, voy a combinar acá los metodos aprendidos para ver los resultados  de una vez, todos
decimales=np.array([0.5, 1.5, 2.5 ,3.5 ,4.5 ,5.5 ,6.5 ,7.5 ,8.5 ,9.5])
print(type(decimales))
print(decimales.dtype)
print(decimales.size)
print(decimales.ndim)
print(decimales.shape)

<class 'numpy.ndarray'>
float64
10
1
(10,)


In [17]:
decimales[0]=1/5 #De esta manera podemos cambiar el primer elemento de la matriz
print(decimales)

[0.2 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [20]:
decimales[9]=9/6 #Acá estamos cambiando el último valor de la matriz
print(decimales)

[0.2 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 1.5]


In [34]:
#También podemos recortar una parte de la matriz usando slicings
decimales_1=decimales[0:5]
print(decimales_1)
type(decimales)
print(decimales_1)

[0.2 1.5 2.5 3.5 4.5]
[0.2 1.5 2.5 3.5 4.5]


<h2>Operaciones básicas con Numpy</h2>
<h3>Bueno ahora vamos a ver como podemos operar los matrices que creamos, creo que esas matrices, se llaman en otros lenguajes arreglos, pero al parecer sirven para lo mismo, es solo una hipotesis no se fien</h3>

#Bueno al parecer vamos a usar la suma de vectores para este ejercicio, rcomiendo estudiar un poco, la recomendación es para mi :D

In [45]:
u=[1,0] #Este es el valor en coordenadas para el primer vector
v=[0,1] #Este es el segundo vector
#PAra hayas el vector z debemos unir la cabeza del primer vector con la cola del sgundo
z=[]#Aún no sabemos el valor de este vector
for n, m in zip(u,v):
    z.append(n-m) #esta es la forma de unir dos vectores sin usar numpu

print(z)

[1, -1]


In [46]:
#Ahora uysemos numpy para sumar los vectores si vemos usando numpy la cosa es mucho más rápida pero también más facil de hacer
c=np.array([1,0])
d=np.array([0,1])
x=c+d
print(x)

[1 1]


In [47]:
#También podemos hacer la resta vectorial solo cambiando el simbolo, vamos a ver
e=np.array([1,0])
f=np.array([0,1])
g=e-f
print(g)

[ 1 -1]


In [48]:
#Veamos ahora como podemos multiplicar un vector por una escalar
vector_1=np.array([1,2]) #Ojo recuerda que para declarar un matriz, se debe declarar el vector, seguido por np.array y el valor del vector
vector_doble=2*vector_1
print(vector_doble)

[2 4]


In [49]:
#Bueno ahora tambien vamos a poder calcular el producto de HAdamard de dos matrices. ojo que solo se puede hacer si las matrices son del mismo tamaño
vector1=np.array([5,7]) #Este es el valor del primer vector
vector2=np.array([8,9]) #Este es el valor del segundo vector
vector_hadamar=vector1*vector2
print(vector_hadamar)


[40 63]


In [52]:
#Bueno ahora vamos a ver como se hace el producto punto con numpy, ojo que el producto punto el la multiplicación de cada uno de los 
#elementos de las dos matrices (en este caso), y la suma de esos productos, por lo tanto debe dar una escalar, otra cosa que aprendí es que
#dot en espaol es punto
#Veamos como se hace
vector1_1=np.array([1,2]) #Declaramos el primer vector
vector1_2=np.array([3,1]) #Declaramos el segundo vector
producto_punt=np.dot(vector1_1,vector1_2) #Usamos un metodo de numpy para calcular el producto punto de lso vectores
print(producto_punt) #imprimimos la escalar resultante




5


In [54]:
#Tambien puedo agregar una constante a un arreglo de la siguiente maanera
arreglo=np.array([0,1,2,3,4,5,6,7,8,9]) #Definimos el arreglo
arreglo_sumado=arreglo+1 #Usamos esta sentencia para agrgarle una escalar a cada elemento del arreglo y lo guardamos en una variable nueva
print(arreglo_sumado) #Imprimimos la nueva variable

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#