<h1>En este caso veremos la biblioteca numpy, pero con arreglos de dos dimensiones</h1>

In [1]:
import numpy as np
#Bueno empecemos
lista_1=[[11,12,13],[21,22,23],[31,31,33]] #Acá tenemos declarada tres listas entre una lista
matriz_1_2d= np.array(lista_1) #Acá con la ayuda de numpy lo que hacemos es convertir lista en una matriz


In [2]:
#empecemos a usar los metodos de numpy para obtener información de las matrices
matriz_1_2d.ndim #Este metodo nos ayuda a saber las dimensiones de la matriz, recordemos que pueden existir matrices de multiples dimensiones, en este caso solo son dos
matriz_1_2d.shape #Este metodo devuelve el número de filas y de columas de la matriz en este caso es una matriz 3 por 3
matriz_1_2d.size #Este metodo me muestra el tamaño de la matriz en su totalidad, es decir cuenta los elementos de la matriz

9

Para ingresar a un daro en particular de una matriz 2d podemos usar el indice, hay que tener claro que las filas y las columnas empiezan por cero, voy  aponer una tabla para que haya un ejemplo más grafico
<table>
      <tr>
        <td>[0][0]</td>
        <td>[0][1]</td>
        <td>[0][2]</td>
      </tr>
      <tr>
        <td>[1][0]</td>
        <td>[1][1]</td>
        <td>[1][2]</td>
      </tr>
      <tr>
        <td>[2][0]</td>
        <td>[2][1]</td>
        <td>[2][2]</td>
      </tr>
    </table>

In [3]:
#llamemos algunos valores de la matriz 
matriz_1_2d[0][0]

11

In [4]:
#llamemos algunos valores de la matriz 
matriz_1_2d[1][1]

22

In [5]:
#Podemos también cortar las matrices usando el slicing, aunque es un poco diferente
matriz_1_2d[0,0:2] #el primer valor es el de la final, en este caso toda fila 0, el segundo valor es el de las columnas, en este caso la columna de la 0 a la 2, pero recordemos que en el slicing la última no se muestra

array([11, 12])

In [6]:
#Hagamos otro ejemplo
matriz_1_2d[0:2,2]

array([13, 23])

In [7]:
#Usando numpy, podemos sumar matrices luego de declararlas, miremos
lista_2=[[2,4,6],[8,10,12],[14,16,18]]
matriz_2_2d=np.array(lista_2)
matriz_total=matriz_1_2d+matriz_2_2d
print(matriz_1_2d)
print(        "+"        )
print(matriz_2_2d)
print(        "="        )
print(matriz_total)

[[11 12 13]
 [21 22 23]
 [31 31 33]]
+
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=
[[13 16 19]
 [29 32 35]
 [45 47 51]]


In [8]:
#Ahora lo que vamos a hacer es multiplicar una matriz por una escalar, veamos como 
matriz_multiplicada=2*matriz_total
print(matriz_total)
print("* 2")
print(matriz_multiplicada)

[[13 16 19]
 [29 32 35]
 [45 47 51]]
* 2
[[ 26  32  38]
 [ 58  64  70]
 [ 90  94 102]]


In [9]:
#Ahora calculemos una miltiplicación drirecta entre matrices, producto Hadamard
matriz_hadamard=matriz_multiplicada*matriz_total
print(matriz_multiplicada)
print("* Hadamard")
print(matriz_total)
print("resultado")
print(matriz_hadamard)


[[ 26  32  38]
 [ 58  64  70]
 [ 90  94 102]]
* Hadamard
[[13 16 19]
 [29 32 35]
 [45 47 51]]
resultado
[[ 338  512  722]
 [1682 2048 2450]
 [4050 4418 5202]]


In [15]:
#bueno hagamos una multiplicación de matrices, debemos recordar que para hacer una multiplicacion de matrices, el numero de columnas de la primera matriz, debe ser igual al númerod e filas de la segunda matriz
matriz_1=np.array([[2,4,6],[8,10,12]])
matriz_2=np.array([[5,3],[7,5],[9,8]])
print(matriz_1)
print(matriz_2)
matriz_multiplicada=np.dot(matriz_1,matriz_2)#Así multiplicamos dos matrices
print(matriz_multiplicada)

[[ 2  4  6]
 [ 8 10 12]]
[[5 3]
 [7 5]
 [9 8]]
[[ 92  74]
 [218 170]]


In [16]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [17]:

X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3] #Rfecuerda que acá lo que hacemos es, como cortar la matriz, seleccionamos la primera fila y las columnas 2 y 3
out


array([0, 1])

In [20]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
print(Z)

[[2 2]
 [2 2]]
